export const tokenListDataApi = [
  {
    id: 1,
    token_number: 124,
    subject: "Order Problem",
    last_response: "28/09/24",
    priority: "High",
    status: "Closed",
  },
  {
    id: 2,
    token_number: 125,
    subject: "Payment Issue",
    last_response: "27/09/24",
    priority: "Medium",
    status: "Open",
  },
  {
    id: 3,
    token_number: 126,
    subject: "Login Failed",
    last_response: "26/09/24",
    priority: "Low",
    status: "In Progress",
  },
  {
    id: 4,
    token_number: 127,
    subject: "Account Suspension",
    last_response: "25/09/24",
    priority: "High",
    status: "Closed",
  },
  {
    id: 5,
    token_number: 128,
    subject: "Refund Request",
    last_response: "24/09/24",
    priority: "Medium",
    status: "Open",
  },
  {
    id: 6,
    token_number: 129,
    subject: "Delayed Shipping",
    last_response: "23/09/24",
    priority: "Low",
    status: "Closed",
  },
  {
    id: 7,
    token_number: 130,
    subject: "Product Defect",
    last_response: "22/09/24",
    priority: "High",
    status: "In Progress",
  },
  {
    id: 8,
    token_number: 131,
    subject: "Invoice Issue",
    last_response: "21/09/24",
    priority: "Medium",
    status: "Closed",
  },
  {
    id: 9,
    token_number: 132,
    subject: "Subscription Cancellation",
    last_response: "20/09/24",
    priority: "Low",
    status: "Open",
  },
  {
    id: 10,
    token_number: 133,
    subject: "Discount Code Problem",
    last_response: "19/09/24",
    priority: "Medium",
    status: "Closed",
  },
  {
    id: 11,
    token_number: 134,
    subject: "Order Tracking Issue",
    last_response: "18/09/24",
    priority: "Low",
    status: "Open",
  },
  {
    id: 12,
    token_number: 135,
    subject: "Technical Support",
    last_response: "17/09/24",
    priority: "High",
    status: "In Progress",
  },
  {
    id: 13,
    token_number: 136,
    subject: "Broken Item Received",
    last_response: "16/09/24",
    priority: "Medium",
    status: "Closed",
  },
  {
    id: 14,
    token_number: 137,
    subject: "Failed Transaction",
    last_response: "15/09/24",
    priority: "High",
    status: "Open",
  },
  {
    id: 15,
    token_number: 138,
    subject: "Profile Update Error",
    last_response: "14/09/24",
    priority: "Low",
    status: "Closed",
  },
  {
    id: 16,
    token_number: 139,
    subject: "App Crash",
    last_response: "13/09/24",
    priority: "High",
    status: "In Progress",
  },
  {
    id: 17,
    token_number: 140,
    subject: "Shipping Address Change",
    last_response: "12/09/24",
    priority: "Medium",
    status: "Open",
  },
  {
    id: 18,
    token_number: 141,
    subject: "Email Notification Issue",
    last_response: "11/09/24",
    priority: "Low",
    status: "Closed",
  },
  {
    id: 19,
    token_number: 142,
    subject: "Password Reset",
    last_response: "10/09/24",
    priority: "High",
    status: "In Progress",
  },
  {
    id: 20,
    token_number: 143,
    subject: "Order Cancellation",
    last_response: "09/09/24",
    priority: "Medium",
    status: "Open",
  },
  {
    id: 21,
    token_number: 144,
    subject: "Wrong Item Received",
    last_response: "08/09/24",
    priority: "High",
    status: "Closed",
  },
  {
    id: 22,
    token_number: 145,
    subject: "Duplicate Charges",
    last_response: "07/09/24",
    priority: "Medium",
    status: "Open",
  },
  {
    id: 23,
    token_number: 146,
    subject: "Complaint Registration",
    last_response: "06/09/24",
    priority: "Low",
    status: "In Progress",
  },
  {
    id: 24,
    token_number: 147,
    subject: "Refund Delay",
    last_response: "05/09/24",
    priority: "High",
    status: "Closed",
  },
  {
    id: 25,
    token_number: 148,
    subject: "App Feature Request",
    last_response: "04/09/24",
    priority: "Low",
    status: "Open",
  },
  {
    id: 26,
    token_number: 149,
    subject: "Out of Stock Item",
    last_response: "03/09/24",
    priority: "Medium",
    status: "Closed",
  },
  {
    id: 27,
    token_number: 150,
    subject: "Promotional Offer Inquiry",
    last_response: "02/09/24",
    priority: "Low",
    status: "In Progress",
  },
  {
    id: 28,
    token_number: 151,
    subject: "Multiple Orders Error",
    last_response: "01/09/24",
    priority: "High",
    status: "Closed",
  },
  {
    id: 29,
    token_number: 152,
    subject: "Product Not Delivered",
    last_response: "31/08/24",
    priority: "High",
    status: "Open",
  },
  {
    id: 30,
    token_number: 153,
    subject: "Membership Cancellation",
    last_response: "30/08/24",
    priority: "Medium",
    status: "Closed",
  },
];
