export const ProductListAdminApi = [
  {
    id: "p-157",
    productName: "Fashionable Tote Bag RM 14",
    category: "Beauty",
    stock: 21,
    variant: [
      { color: "Black", quantity: 14 },
      { color: "White", quantity: 20 },
      { color: "Red", quantity: 18 },
    ],
    price: {
      buying: 600,
      resell: 590,
      retail: 570,
      suggested: 650,
    },
    rating: 4.5,
    reviews: 44,
    image: "prod.jpg",
  },
  {
    id: "p-158",
    productName: "Elegant Handbag RM 12",
    category: "Fashion",
    stock: 15,
    variant: [
      { color: "Brown", quantity: 10 },
      { color: "Black", quantity: 5 },
    ],
    price: {
      buying: 500,
      resell: 490,
      retail: 470,
      suggested: 550,
    },
    rating: 4.2,
    reviews: 34,
    image: "prod2.jpg",
  },
  {
    id: "p-159",
    productName: "Classic Wallet RM 08",
    category: "Accessories",
    stock: 30,
    variant: [
      { color: "Black", quantity: 15 },
      { color: "Tan", quantity: 15 },
    ],
    price: {
      buying: 300,
      resell: 290,
      retail: 270,
      suggested: 350,
    },
    rating: 4.7,
    reviews: 50,
    image: "prod3.jpg",
  },
  {
    id: "p-160",
    productName: "Men's Leather Shoes RM 10",
    category: "Footwear",
    stock: 10,
    variant: [
      { color: "Black", quantity: 5 },
      { color: "Brown", quantity: 5 },
    ],
    price: {
      buying: 1200,
      resell: 1150,
      retail: 1100,
      suggested: 1250,
    },
    rating: 4.3,
    reviews: 29,
    image: "prod4.jpg",
  },
  {
    id: "p-161",
    productName: "Summer Dress RM 02",
    category: "Clothing",
    stock: 45,
    variant: [
      { color: "Yellow", quantity: 20 },
      { color: "Blue", quantity: 25 },
    ],
    price: {
      buying: 800,
      resell: 790,
      retail: 770,
      suggested: 850,
    },
    rating: 4.8,
    reviews: 60,
    image: "prod5.jpg",
  },

  {
    id: "p-162",
    productName: "Modern Sunglasses RM 06",
    category: "Accessories",
    stock: 25,
    variant: [
      { color: "Black", quantity: 15 },
      { color: "Silver", quantity: 10 },
    ],
    price: {
      buying: 400,
      resell: 390,
      retail: 370,
      suggested: 450,
    },
    rating: 4.6,
    reviews: 48,
    image: "prod6.jpg",
  },
  {
    id: "p-163",
    productName: "Kids' Sneakers RM 11",
    category: "Footwear",
    stock: 35,
    variant: [
      { color: "Red", quantity: 15 },
      { color: "Blue", quantity: 20 },
    ],
    price: {
      buying: 900,
      resell: 890,
      retail: 870,
      suggested: 950,
    },
    rating: 4.1,
    reviews: 25,
    image: "prod7.jpg",
  },
  {
    id: "p-164",
    productName: "Luxury Watch RM 08",
    category: "Accessories",
    stock: 5,
    variant: [
      { color: "Gold", quantity: 3 },
      { color: "Silver", quantity: 2 },
    ],
    price: {
      buying: 2000,
      resell: 1900,
      retail: 1800,
      suggested: 2100,
    },
    rating: 4.9,
    reviews: 90,
    image: "prod8.jpg",
  },
  {
    id: "p-165",
    productName: "Casual T-shirt RM 09",
    category: "Clothing",
    stock: 55,
    variant: [
      { color: "White", quantity: 25 },
      { color: "Black", quantity: 30 },
    ],
    price: {
      buying: 250,
      resell: 240,
      retail: 220,
      suggested: 300,
    },
    rating: 4.4,
    reviews: 38,
    image: "prod9.jpg",
  },
  {
    id: "p-166",
    productName: "Stylish Cap RM 07",
    category: "Accessories",
    stock: 40,
    variant: [
      { color: "Blue", quantity: 20 },
      { color: "Red", quantity: 20 },
    ],
    price: {
      buying: 150,
      resell: 140,
      retail: 130,
      suggested: 180,
    },
    rating: 4.0,
    reviews: 22,
    image: "prod10.jpg",
  },
  {
    id: "p-167",
    productName: "Running Shoes RM 04",
    category: "Footwear",
    stock: 28,
    variant: [
      { color: "White", quantity: 18 },
      { color: "Blue", quantity: 10 },
    ],
    price: {
      buying: 1000,
      resell: 950,
      retail: 920,
      suggested: 1100,
    },
    rating: 4.3,
    reviews: 35,
    image: "prod11.jpg",
  },
  {
    id: "p-168",
    productName: "Winter Jacket RM 15",
    category: "Clothing",
    stock: 13,
    variant: [
      { color: "Gray", quantity: 6 },
      { color: "Black", quantity: 7 },
    ],
    price: {
      buying: 1500,
      resell: 1450,
      retail: 1400,
      suggested: 1600,
    },
    rating: 4.7,
    reviews: 58,
    image: "prod12.jpg",
  },
  {
    id: "p-169",
    productName: "Leather Belt RM 02",
    category: "Accessories",
    stock: 22,
    variant: [
      { color: "Black", quantity: 12 },
      { color: "Brown", quantity: 10 },
    ],
    price: {
      buying: 200,
      resell: 190,
      retail: 180,
      suggested: 220,
    },
    rating: 4.5,
    reviews: 26,
    image: "prod13.jpg",
  },
  {
    id: "p-170",
    productName: "Silk Scarf RM 10",
    category: "Fashion",
    stock: 18,
    variant: [
      { color: "Pink", quantity: 10 },
      { color: "Purple", quantity: 8 },
    ],
    price: {
      buying: 600,
      resell: 580,
      retail: 550,
      suggested: 650,
    },
    rating: 4.4,
    reviews: 33,
    image: "prod14.jpg",
  },
  {
    id: "p-171",
    productName: "Designer Sunglasses RM 05",
    category: "Accessories",
    stock: 12,
    variant: [
      { color: "Black", quantity: 6 },
      { color: "Gold", quantity: 6 },
    ],
    price: {
      buying: 1200,
      resell: 1150,
      retail: 1100,
      suggested: 1300,
    },
    rating: 4.9,
    reviews: 62,
    image: "prod15.jpg",
  },
  {
    id: "p-172",
    productName: "Cotton Shirt RM 09",
    category: "Clothing",
    stock: 60,
    variant: [
      { color: "White", quantity: 30 },
      { color: "Gray", quantity: 30 },
    ],
    price: {
      buying: 400,
      resell: 390,
      retail: 360,
      suggested: 450,
    },
    rating: 4.2,
    reviews: 40,
    image: "prod16.jpg",
  },
  {
    id: "p-173",
    productName: "Formal Pants RM 08",
    category: "Clothing",
    stock: 18,
    variant: [
      { color: "Black", quantity: 9 },
      { color: "Navy Blue", quantity: 9 },
    ],
    price: {
      buying: 900,
      resell: 880,
      retail: 850,
      suggested: 950,
    },
    rating: 4.6,
    reviews: 48,
    image: "prod17.jpg",
  },
  {
    id: "p-174",
    productName: "Leather Backpack RM 12",
    category: "Fashion",
    stock: 22,
    variant: [
      { color: "Brown", quantity: 12 },
      { color: "Black", quantity: 10 },
    ],
    price: {
      buying: 2000,
      resell: 1900,
      retail: 1800,
      suggested: 2100,
    },
    rating: 4.8,
    reviews: 65,
    image: "prod18.jpg",
  },
  {
    id: "p-175",
    productName: "High-Top Sneakers RM 06",
    category: "Footwear",
    stock: 35,
    variant: [
      { color: "Red", quantity: 15 },
      { color: "Black", quantity: 20 },
    ],
    price: {
      buying: 1000,
      resell: 950,
      retail: 920,
      suggested: 1100,
    },
    rating: 4.1,
    reviews: 28,
    image: "prod19.jpg",
  },
  {
    id: "p-176",
    productName: "Denim Jeans RM 04",
    category: "Clothing",
    stock: 50,
    variant: [
      { color: "Blue", quantity: 30 },
      { color: "Black", quantity: 20 },
    ],
    price: {
      buying: 800,
      resell: 780,
      retail: 750,
      suggested: 850,
    },
    rating: 4.3,
    reviews: 40,
    image: "prod20.jpg",
  },
  {
    id: "p-177",
    productName: "Casual Sneakers RM 07",
    category: "Footwear",
    stock: 40,
    variant: [
      { color: "White", quantity: 25 },
      { color: "Black", quantity: 15 },
    ],
    price: {
      buying: 1100,
      resell: 1050,
      retail: 1000,
      suggested: 1200,
    },
    rating: 4.7,
    reviews: 54,
    image: "prod21.jpg",
  },
  {
    id: "p-178",
    productName: "Basic Hoodie RM 03",
    category: "Clothing",
    stock: 32,
    variant: [
      { color: "Gray", quantity: 20 },
      { color: "Black", quantity: 12 },
    ],
    price: {
      buying: 700,
      resell: 680,
      retail: 650,
      suggested: 750,
    },
    rating: 4.5,
    reviews: 37,
    image: "prod22.jpg",
  },
  {
    id: "p-179",
    productName: "Waterproof Jacket RM 05",
    category: "Clothing",
    stock: 15,
    variant: [
      { color: "Navy", quantity: 8 },
      { color: "Gray", quantity: 7 },
    ],
    price: {
      buying: 1300,
      resell: 1250,
      retail: 1200,
      suggested: 1400,
    },
    rating: 4.8,
    reviews: 55,
    image: "prod23.jpg",
  },
  {
    id: "p-180",
    productName: "Smart Watch RM 12",
    category: "Accessories",
    stock: 5,
    variant: [
      { color: "Black", quantity: 3 },
      { color: "Silver", quantity: 2 },
    ],
    price: {
      buying: 2500,
      resell: 2400,
      retail: 2300,
      suggested: 2600,
    },
    rating: 4.9,
    reviews: 70,
    image: "prod24.jpg",
  },
  {
    id: "p-181",
    productName: "Leather Wallet RM 03",
    category: "Accessories",
    stock: 20,
    variant: [
      { color: "Brown", quantity: 10 },
      { color: "Black", quantity: 10 },
    ],
    price: {
      buying: 350,
      resell: 340,
      retail: 320,
      suggested: 400,
    },
    rating: 4.3,
    reviews: 33,
    image: "prod25.jpg",
  },
  {
    id: "p-182",
    productName: "Fitness Tracker RM 10",
    category: "Accessories",
    stock: 12,
    variant: [
      { color: "Black", quantity: 8 },
      { color: "Gray", quantity: 4 },
    ],
    price: {
      buying: 1800,
      resell: 1700,
      retail: 1600,
      suggested: 1900,
    },
    rating: 4.8,
    reviews: 45,
    image: "prod26.jpg",
  },
  {
    id: "p-183",
    productName: "Sports Shorts RM 07",
    category: "Clothing",
    stock: 28,
    variant: [
      { color: "Blue", quantity: 15 },
      { color: "Black", quantity: 13 },
    ],
    price: {
      buying: 500,
      resell: 490,
      retail: 470,
      suggested: 550,
    },
    rating: 4.2,
    reviews: 38,
    image: "prod27.jpg",
  },
  {
    id: "p-184",
    productName: "Printed T-shirt RM 08",
    category: "Clothing",
    stock: 60,
    variant: [
      { color: "Red", quantity: 25 },
      { color: "White", quantity: 35 },
    ],
    price: {
      buying: 250,
      resell: 240,
      retail: 220,
      suggested: 300,
    },
    rating: 4.1,
    reviews: 40,
    image: "prod28.jpg",
  },
  {
    id: "p-185",
    productName: "Flip Flops RM 04",
    category: "Footwear",
    stock: 35,
    variant: [
      { color: "Black", quantity: 20 },
      { color: "Red", quantity: 15 },
    ],
    price: {
      buying: 200,
      resell: 190,
      retail: 170,
      suggested: 220,
    },
    rating: 4.4,
    reviews: 25,
    image: "prod29.jpg",
  },
  {
    id: "p-186",
    productName: "Stylish Backpack RM 09",
    category: "Fashion",
    stock: 18,
    variant: [
      { color: "Gray", quantity: 10 },
      { color: "Blue", quantity: 8 },
    ],
    price: {
      buying: 1500,
      resell: 1450,
      retail: 1400,
      suggested: 1600,
    },
    rating: 4.6,
    reviews: 50,
    image: "prod30.jpg",
  },
];
